### ISSUE TITLE
[Todo][Frontend]在Request to API with the access_token部分，支持其他的Method

### ISSUE THREAD

**Issue by freedomkk-qfeng** [ECNU/Open-OAuth2Playground#19]
除了 GET 之外，增加其他 method 的支持。

同时要考虑自定义 header ，自定义 content-type 和 request body 传入的支持

可以参考 google oauth2.0 playground 的实现风格

**Comment by Laceyoo** [comment]
related PR: https://github.com/ECNU/Open-OAuth2Playground/pull/23
