### ISSUE TITLE
您好，麻烦问下我本地测试时，Client Id和Client Secret 怎么配置呢？我自己随便填可以吗

### ISSUE THREAD

**Issue by sceosun** [ECNU/Open-OAuth2Playground#22]
您好，麻烦问下我本地测试时，Client Id和Client Secret 怎么配置呢？我自己随便填可以吗？我随便填后，点击go按钮，重定向到另一个地址后显示404;
![oauth](https://github.com/ECNU/Open-OAuth2Playground/assets/108566400/e8db7876-ed18-4090-addf-31bb8326a982)

**Comment by freedomkk-qfeng** [comment]
你需要有个 oauth2 的 server，可以尝试用开源的 [apereo cas](https://apereo.github.io/cas/6.6.x/protocol/OAuth-Protocol.html) 的项目来做一个本地的 oauth2 服务器。

或者可以尝试找一个生产的 oauth2 服务，并申请一个 client_id 和 client_secret，同时申请将自己本地测试IP地址添加到 oauth2 服务这个 client 的回调白名单中。

**Comment by sceosun** [comment]
好的，感谢
