### ISSUE TITLE
[BUG][frontend]当 rawjson 没有正确内容时，前端会 Uncaught runtime errors:

### ISSUE THREAD

**Issue by freedomkk-qfeng** [ECNU/Open-OAuth2Playground#5]
如果 OAuth2 Server 响应异常，此时 rawjson 无法解析到正常的请求返回，前端解析 token 出错时会 Uncaught runtime errors:

此时 request 和 response 部分还是有正常可解析的内容，应该继续正常解析，便于开发者判断问题

需要增加一个容错处理

**Comment by Laceyoo** [comment]
related commit: https://github.com/ECNU/Open-OAuth2Playground/commit/d47801789a00595a0c3a3a33a0a70bd5ec8f7198

**Comment by Laceyoo** [comment]
> me

client mode commit: https://github.com/ECNU/Open-OAuth2Playground/commit/d47801789a00595a0c3a3a33a0a70bd5ec8f7198
